[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "workflango"
version = "1.0.0-rc1"
description = "A reusable Django BPM workflow engine"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "Django>=4.2",
]

[project.optional-dependencies]
dev = [
    "psycopg2-binary",
    "djangorestframework",
    "pdoc",
    "build",
]

[tool.setuptools.packages.find]
include = ["workflango*"]

[tool.setuptools.package-data]
workflango = ["templates/**/*.html", "locale/**/*"]
