# Generated by Django 6.0.6 on 2026-06-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_object', models.PositiveIntegerField()),
                ('phase', models.CharField(max_length=20)),
                ('state_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('transition_type', models.CharField(max_length=20)),
                ('suspended', models.BooleanField(default=False)),
                ('unread', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('content_type_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('impersonated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('next_state', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_previous_state', to='workflango.state')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='states', to=settings.AUTH_USER_MODEL)),
                ('previous_state', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_next_state', to='workflango.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
