# Generated by Django 6.0.6 on 2026-06-29 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflango', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='next_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_previous_state', to='workflango.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='previous_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='_next_state', to='workflango.state'),
        ),
    ]
